version: '3.9'

services:
  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1121
      MYSQL_DATABASE: my_database
      MYSQL_USER: appp
      MYSQL_PASSWORD: appp
    volumes:
      - ./src/main/resource/init.sql:/docker-entrypoint-initdb.d

  springboot:
    build:
      context: ./springboot
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mysql

# あとはここにreact の「npm start」を入れられるなら完成？

  react:  # Reactアプリケーション（フロントエンド）の設定開始
    build:
      context: ./reactapp  # `Backup-docker-compose.yml` から見たビルドコンテキスト
      dockerfile: Dockerfile
    ports:
      - "3000:80"  # ホストのポート3000をコンテナのポート3000にマッピングしまっs
      # - "ホスト側のポート:コンテナ側のポート"
    volumes:
      - ./reactapp/src:/usr/share/nginx/html/src
    depends_on:
      - springboot  # backendサービスが起動している必要があります
volumes:
  db_data:

